// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIry0rbNvfJaxU4b2g5nSHvOPQQ3V3Wk8',
    appId: '1:1079170693126:web:a28ddce50324cef9e86b87',
    messagingSenderId: '1079170693126',
    projectId: 'food-delivery-d071d',
    authDomain: 'food-delivery-d071d.firebaseapp.com',
    storageBucket: 'food-delivery-d071d.appspot.com',
    measurementId: 'G-0QRZLG84BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbWKk9loepkI0FMr3b5DKuBd7eijHTgAU',
    appId: '1:1079170693126:android:c3f6923db5dc67ade86b87',
    messagingSenderId: '1079170693126',
    projectId: 'food-delivery-d071d',
    storageBucket: 'food-delivery-d071d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLlTmEkUCgJLubn_BXEOgd8-N1vhdycUo',
    appId: '1:1079170693126:ios:f1e57b54f8b14e92e86b87',
    messagingSenderId: '1079170693126',
    projectId: 'food-delivery-d071d',
    storageBucket: 'food-delivery-d071d.appspot.com',
    iosClientId: '1079170693126-ltsm762i5i15v5l7i5h1i8lksu6icskm.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodSwipe',
  );
}
